// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sorbdbyxenjjyiiyixuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvcmJkYnl4ZW5qanlpaXlpeHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NjAyMDEsImV4cCI6MjA3NzEzNjIwMX0.6xqLkZn8EVCscliYv0xGPg_UP_ILmwtuN8agfC7WGug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});